INSERT INTO estado (codigo, nome, sigla) VALUES (7, 'Alagoas', 'AL') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (8, 'Amapá', 'AP') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (9, 'Amazonas', 'AM') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (10, 'Ceará', 'CE') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (11, 'Distrito Federal', 'DF') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (12, 'Espírito Santo', 'ES') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (13, 'Maranhão', 'MA') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (14, 'Mato Grosso', 'MT') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (15, 'Mato Grosso do Sul', 'MS') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (16, 'Pará', 'PA') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (17, 'Paraíba', 'PB') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (18, 'Paraná', 'PR') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (19, 'Pernambuco', 'PE') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (20, 'Piauí', 'PI') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (21, 'Rio de Janeiro', 'RJ') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (22, 'Rio Grande do Norte', 'RN') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (23, 'Rio Grande do Sul', 'RS') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (24, 'Rondônia', 'RO') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (25, 'Roraima', 'RR') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (26, 'Sergipe', 'SE') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);
INSERT INTO estado (codigo, nome, sigla) VALUES (27, 'Tocantins', 'TO') ON DUPLICATE KEY UPDATE nome = VALUES(nome), sigla = VALUES(sigla);

INSERT INTO cidade (nome, codigo_estado) SELECT 'Maceió', 7 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Maceió' AND codigo_estado = 7);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Arapiraca', 7 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Arapiraca' AND codigo_estado = 7);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Macapá', 8 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Macapá' AND codigo_estado = 8);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Santana', 8 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Santana' AND codigo_estado = 8);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Manaus', 9 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Manaus' AND codigo_estado = 9);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Parintins', 9 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Parintins' AND codigo_estado = 9);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Fortaleza', 10 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Fortaleza' AND codigo_estado = 10);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Juazeiro do Norte', 10 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Juazeiro do Norte' AND codigo_estado = 10);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Brasília', 11 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Brasília' AND codigo_estado = 11);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Vitória', 12 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Vitória' AND codigo_estado = 12);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Vila Velha', 12 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Vila Velha' AND codigo_estado = 12);
INSERT INTO cidade (nome, codigo_estado) SELECT 'São Luís', 13 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'São Luís' AND codigo_estado = 13);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Imperatriz', 13 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Imperatriz' AND codigo_estado = 13);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Cuiabá', 14 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Cuiabá' AND codigo_estado = 14);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Rondonópolis', 14 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Rondonópolis' AND codigo_estado = 14);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Campo Grande', 15 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Campo Grande' AND codigo_estado = 15);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Dourados', 15 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Dourados' AND codigo_estado = 15);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Belém', 16 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Belém' AND codigo_estado = 16);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Santarém', 16 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Santarém' AND codigo_estado = 16);
INSERT INTO cidade (nome, codigo_estado) SELECT 'João Pessoa', 17 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'João Pessoa' AND codigo_estado = 17);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Campina Grande', 17 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Campina Grande' AND codigo_estado = 17);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Curitiba', 18 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Curitiba' AND codigo_estado = 18);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Londrina', 18 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Londrina' AND codigo_estado = 18);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Maringá', 18 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Maringá' AND codigo_estado = 18);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Recife', 19 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Recife' AND codigo_estado = 19);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Caruaru', 19 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Caruaru' AND codigo_estado = 19);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Teresina', 20 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Teresina' AND codigo_estado = 20);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Parnaíba', 20 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Parnaíba' AND codigo_estado = 20);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Rio de Janeiro', 21 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Rio de Janeiro' AND codigo_estado = 21);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Niterói', 21 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Niterói' AND codigo_estado = 21);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Natal', 22 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Natal' AND codigo_estado = 22);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Mossoró', 22 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Mossoró' AND codigo_estado = 22);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Porto Alegre', 23 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Porto Alegre' AND codigo_estado = 23);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Caxias do Sul', 23 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Caxias do Sul' AND codigo_estado = 23);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Porto Velho', 24 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Porto Velho' AND codigo_estado = 24);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Ji-Paraná', 24 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Ji-Paraná' AND codigo_estado = 24);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Boa Vista', 25 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Boa Vista' AND codigo_estado = 25);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Rorainópolis', 25 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Rorainópolis' AND codigo_estado = 25);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Aracaju', 26 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Aracaju' AND codigo_estado = 26);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Itabaiana', 26 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Itabaiana' AND codigo_estado = 26);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Palmas', 27 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Palmas' AND codigo_estado = 27);
INSERT INTO cidade (nome, codigo_estado) SELECT 'Araguaína', 27 WHERE NOT EXISTS (SELECT 1 FROM cidade WHERE nome = 'Araguaína' AND codigo_estado = 27);
